### ISSUE TITLE
Swift 4 

### ISSUE THREAD

**Issue by sarrathy** [CRAnimation/CRRefresh#12]
Declarations from extensions cannot be overridden yet

**Comment by MikeNatty** [comment]
Have just encountered this. Will attempt a fix.

**Comment by MikeNatty** [comment]
OT and a QUick-n-dirty solution to the other Swift 4 compilation issues:
- declare the UIColor extension methods public. e.g.

```
**public** convenience init(rgba: String, defaultColor: UIColor = UIColor.clear) {
...
}
```
