### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Maryom** [CRAnimation/CRRefresh#3]
Hey,

Thanks for your awesome repo.

I installed it by using CocoaPods, I added this line to my Podfile: `pod 'CRRefresh'`
However, there are many missing files as you can see in the attached image. what is the problem?
I need to use FastAnimator but I can't because all its files didn't install.

<img width="225" alt="screen shot 2017-05-08 at 10 17 38 am" src="https://cloud.githubusercontent.com/assets/3218401/25794100/2c00f07a-33d8-11e7-9a3d-181a8820aa57.png">

**Comment by imwcl** [comment]
You must update your cocoapods local library
```
pod update
```

**Comment by Maryom** [comment]
Great! problem solved. Thanks.
