### ISSUE TITLE
Empty Collection Contents - Unable to refresh

### ISSUE THREAD

**Issue by xguruteam** [CRAnimation/CRRefresh#33]
When UICollectionView is empty or there are a few contents not as many as enough to scroll, CR is unable to refresh.

**Comment by VasApps** [comment]
Set the the collectionView's alwaysBounceVertical property to true

**Comment by xguruteam** [comment]
Hi, VasApps.

Thank you for your help.
it works very well.
UICollectionView seems not alwaysBounceVertical in default.
So I set the UICollectionView's alwaysBounceVertical property to true. Then it works to refresh.

Cheers.

**Comment by VasApps** [comment]
Yeah I had that same issue and realized without any items it doesn't bounce unless that property is set. Glad to help!

Cheers!
